Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  ElasticSearchEndpoint:
    Description: 'ElasticSearch service endpoint'
    Type: 'String'
Resources:
  IndexerFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: 'Run Rekognition detect labels from S3 events and store results in ElasticSearch.'
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: s3://khk-us-east-1/demos/serverless-app-repo/image-indexer.zip
      Timeout: 30
      Environment:
        Variables:
          ELASTICSEARCH_URL: !Ref ElasticSearchEndpoint
      Events:
        S3JpgEvent:
          Type: S3
          Properties:
            Bucket: !Ref ImageBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  -
                    Name: suffix
                    Value: jpg
        S3PngEvent:
          Type: S3
          Properties:
            Bucket: !Ref ImageBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  -
                    Name: suffix
                    Value: png

  ImageBucket:
    Type: 'AWS::S3::Bucket'